# action.yml
name: vault-installer
author: cpanato
description: 'Installs Hashicorp Vault and includes it in your path'
branding:
  icon: 'package'
  color: 'blue'
# This is pinned to the last major release, we have to bump it for each action version.
inputs:
  vault-release:
    description: 'Hashicorp Vault release version to be installed'
    required: false
    default: '1.18.0'
  install-dir:
    description: 'Where to install the Hashicorp Vault binary'
    required: false
    default: '$HOME/.vault'
  use-sudo:
    description: 'set to true if install-dir location requires sudo privs'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    # We verify the version against a SHA **in the published action itself**, not in the GCS bucket.
    - shell: bash
      run: |
        #!/bin/bash
        # vault install script
        shopt -s expand_aliases
        if [ -z "$NO_COLOR" ]; then
          alias log_info="echo -e \"\033[1;32mINFO\033[0m:\""
          alias log_error="echo -e \"\033[1;31mERROR\033[0m:\""
        else
          alias log_info="echo \"INFO:\""
          alias log_error="echo \"ERROR:\""
        fi
        set -e

        mkdir -p ${{ inputs.install-dir }}

        shaprog() {
          case ${{ runner.os }} in
            Linux)
              sha256sum --ignore-missing --check $2
              ;;
            macOS)
              shasum -a256 --ignore-missing --check $2
              ;;
            Windows)
              powershell -command "(Get-FileHash $1 -Algorithm SHA256 | Select-Object -ExpandProperty Hash).ToLower() -eq (Get-Content $2)"
              ;;
            *)
              log_error "unsupported OS ${{ runner.os }}"
              exit 1
              ;;
          esac
        }

        trap "popd >/dev/null" EXIT

        pushd ${{ inputs.install-dir }} > /dev/null

        case ${{ runner.os }} in
          Linux)
            case ${{ runner.arch }} in
              X64)
                desired_vault_filename='vault_${{ inputs.vault-release }}_linux_amd64.zip'
                ;;

              ARM)
                desired_vault_filename='vault_${{ inputs.vault-release }}_linux_arm.zip'
                ;;

              ARM64)
                desired_vault_filename='vault_${{ inputs.vault-release }}_linux_arm64.zip'
                ;;

              *)
                log_error "unsupported architecture $arch"
                exit 1
                ;;
            esac
            ;;

          macOS)
            case ${{ runner.arch }} in
              X64)
                desired_vault_filename='vault_${{ inputs.vault-release }}_darwin_amd64.zip'
                ;;

              ARM64)
                desired_vault_filename='vault_${{ inputs.vault-release }}_darwin_arm64.zip'
                ;;

              *)
                log_error "unsupported architecture $arch"
                exit 1
                ;;
            esac
            ;;

          Windows)
            case ${{ runner.arch }} in
              X64)
                desired_vault_filename='vault_${{ inputs.vault-release }}_windows_amd64.zip'
                ;;
              *)
                log_error "unsupported architecture $arch"
                exit 1
                ;;
            esac
            ;;
          *)
            log_error "unsupported architecture $arch"
            exit 1
            ;;
        esac

        SUDO=
        if "${{ inputs.use-sudo }}" == "true" && command -v sudo >/dev/null; then
          SUDO=sudo
        fi


        semver='^([0-9]+\.){0,2}(\*|[0-9]+)$'
        if [[ ${{ inputs.vault-release }} =~ $semver ]]; then
          log_info "Hashicorp Vault version '${{ inputs.vault-release }}' requested"
        else
          log_error "Unable to validate requested Hashicorp Vault version: '${{ inputs.vault-release }}'"
          exit 1
        fi

        # Download custom Hashicorp Vault
        log_info "Downloading platform-specific version '${{ inputs.vault-release }}' of vault...\n      https://releases.hashicorp.com/vault/${{ inputs.vault-release }}/${desired_vault_filename}"
        $SUDO curl -sL https://releases.hashicorp.com/vault/${{ inputs.vault-release }}/${desired_vault_filename} -o ${desired_vault_filename}
        $SUDO curl -sL https://releases.hashicorp.com/vault/${{ inputs.vault-release }}/vault_${{ inputs.vault-release }}_SHA256SUMS -o SHA256SUMS
        if [[ ${{ runner.os }} == "Windows" ]]; then
          log_info "Im running here '${{ runner.os }}'"
          filesha256=$(cat SHA256SUMS | grep ${desired_vault_filename} | cut -d' ' -f1)
          echo "$filesha256" > .expected-hash.sha256
          cat .expected-hash.sha256
          shaprog ${desired_vault_filename} .expected-hash.sha256
        else
          log_info "Im running here without windows '${{ runner.os }}'"
          shaprog ${desired_vault_filename} SHA256SUMS
        fi

        ret=$?
        if [[ $retVal -eq 0 ]]; then
          log_info "unpacking!"
          $SUDO unzip "${desired_vault_filename}" -d "${{ inputs.install-dir }}"
          $SUDO rm -f SHA256SUMS
          $SUDO rm -f "${desired_vault_filename}"
          log_info "Installation complete!"
        else
          log_error "Unable to validate vault version: '${{ inputs.vault-release }}'"
          exit 1
        fi
    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: echo "${{ inputs.install-dir }}" >> $GITHUB_PATH
      shell: bash
    - if: ${{ runner.os == 'Windows' }}
      run: echo "${{ inputs.install-dir }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
